version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/adflow2/webapp
permissions:
  - object: /var/www/adflow2/webapp/storage
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www/adflow2/webapp/storage
    owner: apache
    group: apache
    mode: 644
    type:
      - file
  - object: /var/www/adflow2/webapp/bootstrap/cache
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www/adflow2/webapp/bootstrap/cache
    owner: apache
    group: apache
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: bootstrap/scripts/hooks/after-install.sh
  BeforeAllowTraffic:
    - location: bootstrap/scripts/hooks/before-allow-traffic.sh
  AfterAllowTraffic:
    - location: bootstrap/scripts/hooks/after-allow-traffic.sh
