version: 0.2

phases:
  pre_build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 884030823485.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t hellodelvinpoulo .
      - docker tag hellodelvinpoulo:latest 884030823485.dkr.ecr.ap-northeast-1.amazonaws.com/hellodelvinpoulo:latest

  post_build:
    commands:
      - docker push 884030823485.dkr.ecr.ap-northeast-1.amazonaws.com/hellodelvinpoulo:latest
